### ISSUE TITLE
Diagram/pictures

### ISSUE THREAD

**Issue by akinnee** [kayno/arduinolifx#3]
This looks awesome! Can you please post and overhead picture of your wiring or a diagram (you could use http://fritzing.org to make a diagram), as well as a list of components used? I noticed on your YouTube vid you're using some integrated circuits to drive LED strips.

**Comment by bertouttier** [comment]
Hi Akinnee,

The schematics of the hardware that we used can be found [here](https://github.com/phyx-be/ESP12_RGBW). It is a custom board developed by [Wim Van Gool](https://github.com/Brubacker) based on the ESP12.

Kind regards,
Bert

**Comment by kayno** [comment]
@akinnee assuming you mean this video https://www.youtube.com/watch?v=Ij0KbcTmcMI? That was done using just one of those ICs (the other was just a spare stuck in the breadboard. The IC is a ULN2003A, which wikipedia describes as "[an array of seven NPN Darlington transistors capable of 500 mA, 50 V output.](https://en.wikipedia.org/wiki/ULN2003A)". The wiring was as follows:

![arduinolifx-video-breadboard_bb](https://cloud.githubusercontent.com/assets/184464/22880742/76504320-f237-11e6-8954-71c2c9fa227a.png)

I have since changed to using P16NF06 darlington transistors (3 of) instead of the ULN2003A, to drive a 5m LED strip (with power injection both ends).

**Comment by akinnee** [comment]
Awesome! Thanks!
